### ISSUE TITLE
"slightly less toy example" returns error

### ISSUE THREAD

**Issue by zevav** [pybee/toga-core#1]
```python
File "t.py", line 35, in build
    box.style(flex_direction='column', padding_top=10)
TypeError: 'CSSNode' object is not callable
```

**Comment by freakboy3742** [comment]
Are you able to provide a bit more detail here - In particular, your operating system, and the package versions you have installed.

**Comment by manna422** [comment]
i ran into the same issue.
replacing all instanced of `style(...)` with `style.set(...)` in toga-core/docs/tutorial/tutorial-1.rst resolves this.

PS @freakboy3742 the beeware project is amazing. Keep up the good work!

**Comment by freakboy3742** [comment]
Oh - wait - *now* I see it. Yes - that's a typo in the tutorial. I'll get it fixed. Thanks for the report @zevav, and apologies for not seeing the problem on first read.
